# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47c44a6f44966cda319122ea4c788ea23b8337889ab4c694d063a35e19870671b33de1562757cc5fb42be336fa78f8fdb99acb59cd303623ee0cff8cbcf3f880

test:
  secret_key_base: 1e5506ac59f40b9358946b7c593073825959713fb2c9d63c53a0ed6dfd061a3f394969a679826b3559dec932eb538e0a7e6455a18ede2f6cd1729c18df9b040b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
